# Generated by Django 5.1 on 2024-08-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
        ('users', '0002_position_remove_user_avatar_remove_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='task_tracker.task', verbose_name='задачи'),
        ),
    ]
