# Generated by Django 5.1 on 2024-08-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
        ('users', '0003_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='task_tracker.task', verbose_name='задачи'),
        ),
    ]
