# Generated by Django 5.1 on 2024-08-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_alter_status_name'),
        ('users', '0006_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='users', to='task_tracker.task', verbose_name='задачи'),
        ),
    ]
