# Generated by Django 5.1 on 2024-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('task', '0002_task_created_at_task_is_taken_task_parent_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='task.task'),
        ),
    ]
