# Generated by Django 5.1 on 2024-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_tasks'),
        ('task', '0002_task_created_at_task_is_taken_task_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='task.task'),
        ),
    ]
