# Generated by Django 5.1 on 2024-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('open', 'открыта'), ('in_progress', 'в процессе'), ('resolved', 'решена'), ('closed', 'закрыта')], max_length=200, verbose_name='наименование'),
        ),
    ]
